## Notebook 2 – Data Inspection

### 1. Number of Rows

The number of rows refers to the **total number of records or observations** present in a dataset.

In simple words, it tells us how many records are stored in a dataset.

| Student_ID | Name    | Age | Gender | Department | Attendance | Study_Hours | Marks |
| ---------: | ------- | --: | ------ | ---------- | ---------: | ----------: | ----: |
|        101 | Ravi    |  21 | Male   | CSE        |         85 |           4 |    78 |
|        102 | Priya   |  22 | Female | ECE        |         92 |           6 |    91 |
|        103 | Kumar   |  20 | Male   | CSE        |         75 |           3 |    65 |
|        104 | Anjali  |  21 | Female | IT         |         88 |           5 |    84 |
|        105 | Rahul   |  23 | Male   | ECE        |         68 |           2 |    55 |

- This dataset contains 5 rows of student records.

- Each row represents one student's information.

### 2. Number of Columns

The number of columns represents the total number of features or variables in the dataset.

Each column contains a specific type of information.

| Student_ID | Name  | Age | Marks |
| ---------- | ----- | --: | ----: |
| 101        | Ravi  |  21 |    78 |
| 102        | Priya |  22 |    91 |
| 103        | Kumar |  20 |    65 |

This dataset contains 4 columns:

- Student_ID
- Name
- Age
- Marks

Each column represents a particular attribute of the students.

For example:

Age stores students' ages.
    
Study_Hours stores the number of hours students study.
    
Marks stores students' examination marks.

### 3. Data Types

Data types describe the kind of values stored in a column of a dataset.

In simple words, data types tell us whether a column contains numbers, text, dates, Boolean values, or other kinds of information.

#### example

| Student_ID | Name  | Age | Marks |
| ---------- | ----- | --: | ----: |
| 101        | Ravi  |  21 |    78 |
| 102        | Priya |  22 |    91 |
| 103        | Kumar |  20 |    65 |

In this dataset:

Student_ID contains integer values.
    
Name contains text.
    
Age contains integer values.

In [ ]:
df.dtypes

### 4. Column Names

Column names are labels used to identify the information stored in each column of a dataset.

In simple words, column names tell us what kind of information a particular column contains.

Column names represent the labels assigned to each feature in a dataset.

| Student_ID | Name  | Age | Marks |
| ---------- | ----- | --: | ----: |
| 101        | Ravi  |  21 |    78 |
| 102        | Priya |  22 |    91 |
| 103        | Kumar |  20 |    65 |

Student_ID identifies each student.

Name contains students' names.

Age contains students' ages.

Marks contains Students marks.

In [ ]:
df.columns  #  returns all teh columns in the dataset

- Convert to List

list(df.columns)

### 5. Index

The Index is a unique label assigned to each row in a DataFrame.

By default, Pandas assigns numeric indices starting from 0.

In [1]:
import pandas as pd

data = {
    "Name": ["Hari", "Kumar", "Ravi", "Priya"],
    "Age": [22, 25, 23, 24],
    "Salary": [25000, 35000, 30000, 40000]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Salary
0   Hari   22   25000
1  Kumar   25   35000
2   Ravi   23   30000
3  Priya   24   40000

#### How to Inspect the Index?

In [2]:
df.index

RangeIndex(start=0, stop=4, step=1)

#### Assign a Custom Index

You can assign your own index labels to the rows.

In [3]:
df.index = ["A", "B", "C", "D"]

print(df)

    Name  Age  Salary
A   Hari   22   25000
B  Kumar   25   35000
C   Ravi   23   30000
D  Priya   24   40000

#### Reset the Index

To restore the default numerical index:

In [ ]:
df.reset_index(inplace=True)

| Attribute/Method            | Purpose                                                |
| --------------------------- | ------------------------------------------------------ |
| `df.index`                  | View the index                                         |
| `df.index = [...]`          | Assign custom index labels                             |
| `df.reset_index()`          | Reset the index and preserve the old index as a column |
| `df.reset_index(drop=True)` | Reset the index without preserving the old index       |
| `df.set_index("Name")`      | Set the `Name` column as the index                     |

### 6. head()

The head() method in Pandas is used to display the first few rows of a DataFrame.

It is commonly used in Exploratory Data Analysis (EDA) to quickly inspect a dataset and understand its structure.

In [4]:
import pandas as pd

data = {
    "Name": ["Hari", "Kumar", "Ravi", "Priya", "Arun", "Sneha"],
    "Age": [22, 25, 23, 24, 26, 21],
    "Salary": [25000, 35000, 30000, 40000, 45000, 28000]
}

df = pd.DataFrame(data)

print(df.head())

    Name  Age  Salary
0   Hari   22   25000
1  Kumar   25   35000
2   Ravi   23   30000
3  Priya   24   40000
4   Arun   26   45000

#### Display a Specific Number of Rows

You can specify how many rows you want to display.

Example 1: Display the first 3 rows

df.head(3)

### 7. tail()

The tail() method in Pandas is used to display the last few rows of a DataFrame.

It is commonly used in Exploratory Data Analysis (EDA) to inspect the last records of a dataset and check whether the data has been loaded correctly.

In [ ]:
import pandas as pd

data = {
    "Name": ["Hari", "Kumar", "Ravi", "Priya", "Arun", "Sneha"],
    "Age": [22, 25, 23, 24, 26, 21],
    "Salary": [25000, 35000, 30000, 40000, 45000, 28000]
}

df = pd.DataFrame(data)

print(df.tail())

#### Display the last 3 rows

df.tail(3)

### 8. sample()

 The sample() method in Pandas is used to select and display a random sample of rows from a DataFrame.

It is useful in Data Inspection and Exploratory Data Analysis (EDA) to examine a random subset of a dataset

In [7]:
df.sample(n=5)

    Name  Age  Salary
3  Priya   24   40000
5  Sneha   21   28000
0   Hari   22   25000
1  Kumar   25   35000
4   Arun   26   45000

####  AI ML use case

In AI/ML, sample() is used to randomly select rows from a dataset to inspect data, understand its distribution, and test data quality.

####  Specify Random State

This code selects 5 random rows from a DataFrame and ensures that you can get the same selection again when you run the code with the same dataset.

In [8]:
df.sample(5, random_state=42)

    Name  Age  Salary
0   Hari   22   25000
1  Kumar   25   35000
5  Sneha   21   28000
2   Ravi   23   30000
4   Arun   26   45000

Understanding each part:

df → Your DataFrame (dataset).

sample(5) → Randomly selects 5 rows from the dataset.

random_state=42 → Ensures that the same random rows are selected each time you run the code, provided the dataset and sampling conditions remain unchanged.

### 9. shape

The shape attribute in Pandas returns the number of rows and columns in a DataFrame.

It is one of the first attributes used after loading a dataset.

#### Example

In [14]:
import pandas as pd

data = {
    "Name": ["Hari", "Kumar", "Ravi", "Priya"],
    "Age": [22, 25, 23, 24],
    "Salary": [25000, 35000, 30000, 40000]
}

df = pd.DataFrame(data)

print(df.shape)

(4, 3)

In [ ]:
df.shape[0] #No of rows

df.shape[1]  # No of columns

### 10. info()

The info() method in Pandas provides a summary of a DataFrame, including the number of rows and columns, column names, non-null values, data types, and memory usage.

It helps us understand:

- Number of rows
- Number of columns
- Column names
- Data types
- Missing values
- Memory usage

#### example:

In [16]:
import pandas as pd

data = {
    "Name": ["Hari", "Kumar", "Ravi", None],
    "Age": [22, 25, None, 24],
    "Salary": [25000, 35000, 30000, 40000]
}

df = pd.DataFrame(data)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      float64
 2   Salary  4 non-null      int64
dtypes: float64(1), int64(1), str(1)
memory usage: 242.0 bytes

**Why is Age a float64 column?**

The Age column contains a missing value (None). Pandas commonly converts integer columns with missing values to float64 because standard NumPy integer types cannot represent missing values directly.

### 11. describe()

The describe() method in Pandas generates descriptive statistics that summarize the distribution of numerical or categorical data in a DataFrame.

It is commonly used in Exploratory Data Analysis (EDA) to understand the characteristics of a dataset.

By default, it summarizes numerical columns in a DataFrame.

#### Example

In [19]:
import pandas as pd

data = {
    "Name": ["Hari", "Kumar", "Ravi", "Priya", "Arun"],
    "Age": [22, 25, 23, 24, 26],
    "Salary": [25000, 35000, 30000, 40000, 45000]
}

df = pd.DataFrame(data)

df.describe()

             Age       Salary
count   5.000000      5.00000
mean   24.000000  35000.00000
std     1.581139   7905.69415
min    22.000000  25000.00000
25%    23.000000  30000.00000
50%    24.000000  35000.00000
75%    25.000000  40000.00000
max    26.000000  45000.00000

#### Include Categorical Columns

To summarize both numerical and categorical columns, use:

For example, if the Name column contains five different names, unique will be 5.

In [18]:

df.describe(include="all")

        Name        Age       Salary
count      5   5.000000      5.00000
unique     5        NaN          NaN
top     Hari        NaN          NaN
freq       1        NaN          NaN
mean     NaN  24.000000  35000.00000
std      NaN   1.581139   7905.69415
min      NaN  22.000000  25000.00000
25%      NaN  23.000000  30000.00000
50%      NaN  24.000000  35000.00000
75%      NaN  25.000000  40000.00000
max      NaN  26.000000  45000.00000

### 12. dtypes

The dtypes attribute in Pandas is used to display the data type of each column in a DataFrame.

It helps us understand what kind of data each column contains before performing data analysis or building AI/ML models.

#### example

In [20]:
df.dtypes  #Identify numerical and categorical features

Name        str
Age       int64
Salary    int64
dtype: object

#### Find numerical columns

This selects columns containing numerical data.

In [21]:
print(df.select_dtypes(include="number"))

   Age  Salary
0   22   25000
1   25   35000
2   23   30000
3   24   40000
4   26   45000

#### Find categorical or text columns

This selects columns with object or category data types.

In [22]:
print(df.select_dtypes(include=["object", "category"]))

    Name
0   Hari
1  Kumar
2   Ravi
3  Priya
4   Arun

C:\Users\Hari\AppData\Local\Temp\ipykernel_4004\75955103.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.select_dtypes(include=["object", "category"]))

### 13. nunique()

The nunique() method in Pandas is used to count the number of unique (distinct) values in a Series or in each column of a DataFrame.

#### Syntax

df.nunique()

By default, it counts unique values in each column and excludes missing values (NaN).

#### example

In [23]:
import pandas as pd

data = {
    "Name": ["Hari", "Kumar", "Ravi", "Hari", "Kumar"],
    "Age": [22, 25, 23, 22, 25],
    "City": ["Chittoor", "Bangalore", "Chittoor", "Chittoor", "Bangalore"]
}

df = pd.DataFrame(data)

print(df.nunique())

Name    3
Age     3
City    2
dtype: int64

- Name has 3 unique values: Hari, Kumar, Ravi.
- Age has 3 unique values: 22, 25, 23.
- City has 2 unique values: Chittoor, Bangalore.

### 14. value_counts()

The value_counts() method in Pandas is used to count how many times each unique value appears in a Series or DataFrame column

#### example

In [25]:

import pandas as pd

data = {
    "Name": ["Hari", "Kumar", "Ravi", "Hari", "Kumar", "Hari"],
    "Age": [22, 25, 23, 22, 25, 22],
    "City": ["Chittoor", "Bangalore", "Chittoor", "Chittoor", "Bangalore", "Chittoor"]
}

df = pd.DataFrame(data)

print(df["City"].value_counts())

City
Chittoor     4
Bangalore    2
Name: count, dtype: int64

In [ ]:
##Includes missing values in the counts.

df["City"].value_counts(dropna=False)

In [ ]:
#Sorts the counts from lowest to highest.

df["City"].value_counts(ascending=True)

### Sample DataFrame with different types of columns

In [26]:
import pandas as pd

# Create Dataset
data = {
    "CustomerID": ["C001", "C002", "C003", "C004", "C005"],
    "Age": [25, 32, 40, 28, 35],
    "MonthlyIncome": [35000, 50000, 65000, 42000, 58000],
    "Gender": ["Male", "Female", "Male", "Female", "Male"],
    "City": ["Hyderabad", "Chennai", "Bangalore", "Mumbai", "Delhi"],
    "ContractType": ["Monthly", "Yearly", "Monthly", "Quarterly", "Yearly"],
    "JoinDate": [
        "2023-01-15",
        "2022-06-20",
        "2021-11-05",
        "2023-05-12",
        "2022-09-18"
    ],
    "LastLoginDate": [
        "2024-01-10",
        "2024-01-08",
        "2024-01-07",
        "2024-01-09",
        "2024-01-06"
    ],
    "Churn": ["No", "Yes", "No", "No", "Yes"]
}

# Create DataFrame
df = pd.DataFrame(data)

# Convert date columns to datetime
df["JoinDate"] = pd.to_datetime(df["JoinDate"])
df["LastLoginDate"] = pd.to_datetime(df["LastLoginDate"])

# Display Dataset
print(df)

  CustomerID  Age  MonthlyIncome  Gender       City ContractType   JoinDate  \
0       C001   25          35000    Male  Hyderabad      Monthly 2023-01-15
1       C002   32          50000  Female    Chennai       Yearly 2022-06-20
2       C003   40          65000    Male  Bangalore      Monthly 2021-11-05
3       C004   28          42000  Female     Mumbai    Quarterly 2023-05-12
4       C005   35          58000    Male      Delhi       Yearly 2022-09-18

  LastLoginDate Churn
0    2024-01-10    No
1    2024-01-08   Yes
2    2024-01-07    No
3    2024-01-09    No
4    2024-01-06   Yes

#### Dataset Analysis

#### 1. Numerical Columns

Numerical columns contain numbers and support mathematical calculations.


Age
    
MonthlyIncome

In [ ]:
df[['Age', 'MonthlyIncome']]

#### Categorical Columns

Categorical columns contain labels or categories.


Gender

City

ContractType

Churn

In [ ]:
df[['Gender', 'City', 'ContractType', 'Churn']]

#### 3. Date/Time Columns

These columns store dates, timestamps, or time-related information.


JoinDate
LastLoginDate

In [ ]:

df[['JoinDate', 'LastLoginDate']]

#### 4. Identifier Columns

Identifier columns uniquely identify each record.


CustomerID

Characteristics:

Unique values
No duplicates
Usually not used for prediction

In [ ]:
df['CustomerID']

#### 5. Potential Target Column

The target variable is what we want to predict : Churn

Possible values: Yes,No

Business Question: Will the customer leave the company?

In [ ]:

df['Churn']